### ISSUE TITLE
Suggestion for moving the repo to the Project section

### ISSUE THREAD

**Issue by howdyAnkit** [iampavangandhi/TheNodeCourse#21]
Hello Pavan,

Could you move this repo to your project section as well? it comes with stickers such as Done, In Progress, and To-Do under it will be easy to navigate and see the deadlines of projects as well.

**Comment by iampavangandhi** [comment]
hey @howdyAnkit as the learning part of the repo is almost over I will not move it into the project section. Will move TradeByte with a separate repo which is linked here also.

**Comment by howdyAnkit** [comment]
yeah, Pavan that will be Awesome...💯💯
